version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.0.0
    steps:
    - checkout
    - run: npm install
    - run: npm start &
    - run: npm test
    - deploy:
        name: digital-ocean
        command: ssh -o "StrictHostKeyChecking no" root@167.71.166.254"cd ~/circleciexpress; git pull; npm install; npm start &"
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/verovaldes/circleciexpress2/compare/d2626c0ec9e9b61b13eb8d458a529a9bccac5dd9...44fa51cd10b219817a317dab514ee3fc499d5fb4
workflows:
  version: 2
  workflow:
    jobs:
    - build
