version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.0.0
    steps:
    - checkout
    - run: npm install
    - run: npm start &
    - run: npm test
    - deploy:
        name: digital-ocean
        command: ssh -o "StrictHostKeyChecking no" root@167.71.166.254"cd ~/circleciexpress; git pull; npm install; npm start &"
workflows:
  version: 2
  workflow:
    jobs:
    - build167.71.166.254"cd ~/circleciexpress; git pull; npm install; npm start &"
  
